#cloud-config

coreos:
  units:
    - name: oem-ens192.network
      content: |
        [Match]
        Name=ens192

        [Network]
        DHCP=v4
        DNS=8.8.8.8
        DNS=8.8.4.4
    - name: vmtoolsd.service
      command: start
      content: |
        [Unit]
        Description=VMware Tools Agent
        Documentation=http://open-vm-tools.sourceforge.net/
        ConditionVirtualization=vmware

        [Service]
        ExecStartPre=/usr/bin/ln -sfT /usr/share/oem/vmware-tools /etc/vmware-tools
        ExecStart=/usr/share/oem/bin/vmtoolsd
        ExecStartPost=/usr/share/oem/bin/vmware-toolbox-cmd timesync enable 
        TimeoutStopSec=5
    - name: niftycloud-coreos-cloudinit.service
      command: restart
      runtime: yes
      content: |
        [Unit]
        After=coreos-setup-environment.service
        After=vmtoolsd.service
        Requires=coreos-setup-environment.service
        Requires=vmtoolsd.service

        [Service]
        Type=oneshot
        EnvironmentFile=/etc/environment
        ExecStart=/usr/share/oem/bin/niftycloud-coreos-cloudinit
    - name: niftycloud-ssh-key.service
      command: restart
      runtime: yes
      content: |
        [Unit]
        Description=Sets SSH key from vmtoolsd
        [Service]
        Type=oneshot
        StandardOutput=journal+console
        ExecStart=/usr/share/oem/bin/niftycloud-ssh-key

  oem:
    id: niftycloud
    name: NIFTY Cloud
    version-id: @@OEM_VERSION_ID@@
    home-url: http://cloud.nifty.com/
    bug-report-url: https://issues.coreos.com
