#cloud-config

coreos:
    units:
      - name: xenstored.service
        command: start
        runtime: yes
        content: |
            [Unit]
            RequiresMountsFor=/proc/xen

            [Service]
            ExecStartPre=/usr/sbin/modprobe xen-evtchn
            ExecStart=/usr/sbin/xenstored --no-fork
            ExecStartPost=/usr/bin/xenstore write /local/domain/0/name Domain-0
            ExecStartPost=/usr/bin/xenstore write /local/domain/0/domid 0
      - name: xenconsoled.service
        command: start
        runtime: yes
        content: |
            [Unit]
            Requires=xenstored.service
            After=xenstored.service

            [Service]
            ExecStart=/usr/sbin/xenconsoled
    oem:
        id: xendom0
        name: Xen Domain0 for Testing
        version-id: @@OEM_VERSION_ID@@
        home-url: https://coreos.com
        bug-report-url: https://issues.coreos.com
