#cloud-config

coreos:
    units:
      - name: nova-agent-auto.service
        command: restart
        runtime: yes
        content: |
          [Unit]
          After=dbus.service
          [Service]
          Environment=HOME=/root
          ExecStartPre=/bin/mount -t proc none /usr/share/oem/nova-agent/proc
          ExecStartPre=/bin/mount -t xenfs none /usr/share/oem/nova-agent/proc/xen
          ExecStartPre=/bin/mount --bind /dev /usr/share/oem/nova-agent/dev
          ExecStartPre=/bin/mount --bind /sys /usr/share/oem/nova-agent/sys
          ExecStart=/usr/bin/chroot /usr/share/oem/nova-agent/ /usr/share/nova-agent/0.0.1.38/sbin/nova-agent -o - -n -l info /usr/share/nova-agent/nova-agent.py
          ExecStopPost=/bin/umount -f /usr/share/oem/nova-agent/sys
          ExecStopPost=/bin/umount -f /usr/share/oem/nova-agent/dev
          ExecStopPost=/bin/umount -f /usr/share/oem/nova-agent/proc/xen
          ExecStopPost=/bin/umount -f /usr/share/oem/nova-agent/proc
      - name: nova-agent-watcher.service
        command: restart
        runtime: yes
        content: |
          [Unit]
          After=dbus.service

          [Service]
          ExecStart=/usr/share/oem/usr/bin/nova-agent-watcher -watch-dir=/usr/share/oem/nova-agent -scripts-dir=/usr/share/oem/usr/bin/
      - name: media-configdrive.mount
        command: restart
        runtime: yes
        content: |
          [Mount]
          What=/dev/disk/by-label/config-2
          Where=/media/configdrive
      - name: cloudinit-configdrive.service
        command: restart
        runtime: yes
        content: |
          [Unit]
          RequiresMountsFor=/media/configdrive
          Requires=coreos-setup-environment.service
          After=coreos-setup-environment.service

          [Service]
          Type=oneshot
          EnvironmentFile=/etc/environment
          ExecStart=/usr/bin/coreos-cloudinit --from-file=/media/configdrive/openstack/latest/user_data
