#cloud-config

coreos:
  units:
    - name: oem-cloudinit.service
      command: restart
      runtime: yes
      content: |
        [Unit]
        Description=Cloudinit from Packet metadata

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/coreos-cloudinit --oem=packet
    - name: oem-phone-home.service
      command: start
      content: |
        [Unit]
        Description=Basic setup tasks to initialize the machine.
        Wants=sys-devices-virtual-net-bond0.device
        After=sys-devices-virtual-net-bond0.device

        [Service]
        Type=oneshot
        ExecStart=/usr/share/oem/bin/phone-home.sh
  oem:
    id: packet
    name: Packet
    version-id: @@OEM_VERSION_ID@@
    home-url: https://packet.net
    bug-report-url: https://github.com/coreos/bugs/issues
